// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BaseTask      string
	DayOfWeek     string
	ScheduledTask string
	ShareTask     string
	User          string
}{
	BaseTask:      "base_task",
	DayOfWeek:     "day_of_week",
	ScheduledTask: "scheduled_task",
	ShareTask:     "share_task",
	User:          "user",
}
