// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDayOfWeeks(t *testing.T) {
	t.Parallel()

	query := DayOfWeeks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDayOfWeeksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDayOfWeeksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DayOfWeeks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDayOfWeeksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DayOfWeekSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDayOfWeeksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DayOfWeekExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DayOfWeek exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DayOfWeekExists to return true, but got false.")
	}
}

func testDayOfWeeksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	dayOfWeekFound, err := FindDayOfWeek(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if dayOfWeekFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDayOfWeeksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DayOfWeeks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDayOfWeeksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DayOfWeeks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDayOfWeeksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	dayOfWeekOne := &DayOfWeek{}
	dayOfWeekTwo := &DayOfWeek{}
	if err = randomize.Struct(seed, dayOfWeekOne, dayOfWeekDBTypes, false, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}
	if err = randomize.Struct(seed, dayOfWeekTwo, dayOfWeekDBTypes, false, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dayOfWeekOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dayOfWeekTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DayOfWeeks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDayOfWeeksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	dayOfWeekOne := &DayOfWeek{}
	dayOfWeekTwo := &DayOfWeek{}
	if err = randomize.Struct(seed, dayOfWeekOne, dayOfWeekDBTypes, false, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}
	if err = randomize.Struct(seed, dayOfWeekTwo, dayOfWeekDBTypes, false, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dayOfWeekOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dayOfWeekTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func dayOfWeekBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func dayOfWeekAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DayOfWeek) error {
	*o = DayOfWeek{}
	return nil
}

func testDayOfWeeksHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DayOfWeek{}
	o := &DayOfWeek{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DayOfWeek object: %s", err)
	}

	AddDayOfWeekHook(boil.BeforeInsertHook, dayOfWeekBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	dayOfWeekBeforeInsertHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.AfterInsertHook, dayOfWeekAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	dayOfWeekAfterInsertHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.AfterSelectHook, dayOfWeekAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	dayOfWeekAfterSelectHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.BeforeUpdateHook, dayOfWeekBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	dayOfWeekBeforeUpdateHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.AfterUpdateHook, dayOfWeekAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	dayOfWeekAfterUpdateHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.BeforeDeleteHook, dayOfWeekBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	dayOfWeekBeforeDeleteHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.AfterDeleteHook, dayOfWeekAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	dayOfWeekAfterDeleteHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.BeforeUpsertHook, dayOfWeekBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	dayOfWeekBeforeUpsertHooks = []DayOfWeekHook{}

	AddDayOfWeekHook(boil.AfterUpsertHook, dayOfWeekAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	dayOfWeekAfterUpsertHooks = []DayOfWeekHook{}
}

func testDayOfWeeksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDayOfWeeksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(dayOfWeekColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDayOfWeekToManyBaseTasks(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DayOfWeek
	var b, c BaseTask

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, baseTaskDBTypes, false, baseTaskColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, baseTaskDBTypes, false, baseTaskColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.DayOfWeekID = a.ID
	c.DayOfWeekID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.BaseTasks().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.DayOfWeekID == b.DayOfWeekID {
			bFound = true
		}
		if v.DayOfWeekID == c.DayOfWeekID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := DayOfWeekSlice{&a}
	if err = a.L.LoadBaseTasks(ctx, tx, false, (*[]*DayOfWeek)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BaseTasks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.BaseTasks = nil
	if err = a.L.LoadBaseTasks(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.BaseTasks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testDayOfWeekToManyAddOpBaseTasks(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DayOfWeek
	var b, c, d, e BaseTask

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, dayOfWeekDBTypes, false, strmangle.SetComplement(dayOfWeekPrimaryKeyColumns, dayOfWeekColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*BaseTask{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, baseTaskDBTypes, false, strmangle.SetComplement(baseTaskPrimaryKeyColumns, baseTaskColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*BaseTask{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBaseTasks(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.DayOfWeekID {
			t.Error("foreign key was wrong value", a.ID, first.DayOfWeekID)
		}
		if a.ID != second.DayOfWeekID {
			t.Error("foreign key was wrong value", a.ID, second.DayOfWeekID)
		}

		if first.R.DayOfWeek != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.DayOfWeek != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.BaseTasks[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.BaseTasks[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.BaseTasks().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testDayOfWeeksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDayOfWeeksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DayOfWeekSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDayOfWeeksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DayOfWeeks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	dayOfWeekDBTypes = map[string]string{`ID`: `int`, `DayOfWeek`: `int`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_                = bytes.MinRead
)

func testDayOfWeeksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(dayOfWeekPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(dayOfWeekAllColumns) == len(dayOfWeekPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDayOfWeeksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(dayOfWeekAllColumns) == len(dayOfWeekPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DayOfWeek{}
	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dayOfWeekDBTypes, true, dayOfWeekPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(dayOfWeekAllColumns, dayOfWeekPrimaryKeyColumns) {
		fields = dayOfWeekAllColumns
	} else {
		fields = strmangle.SetComplement(
			dayOfWeekAllColumns,
			dayOfWeekPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DayOfWeekSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDayOfWeeksUpsert(t *testing.T) {
	t.Parallel()

	if len(dayOfWeekAllColumns) == len(dayOfWeekPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLDayOfWeekUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DayOfWeek{}
	if err = randomize.Struct(seed, &o, dayOfWeekDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DayOfWeek: %s", err)
	}

	count, err := DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, dayOfWeekDBTypes, false, dayOfWeekPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DayOfWeek struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DayOfWeek: %s", err)
	}

	count, err = DayOfWeeks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
