// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ScheduledTask is an object representing the database table.
type ScheduledTask struct { // ID
	ID int64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	// ユーザーID
	UserID int `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	// タイトル
	Title null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	// 内容
	Content null.String `boil:"content" json:"content,omitempty" toml:"content" yaml:"content,omitempty"`
	// 日付
	ScheduledDate time.Time `boil:"scheduled_date" json:"scheduled_date" toml:"scheduled_date" yaml:"scheduled_date"`
	// 開始時間
	StartTime string `boil:"start_time" json:"start_time" toml:"start_time" yaml:"start_time"`
	// 終了時間
	EndTime string `boil:"end_time" json:"end_time" toml:"end_time" yaml:"end_time"`
	// 作成日時
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	// 更新日時
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *scheduledTaskR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L scheduledTaskL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ScheduledTaskColumns = struct {
	ID            string
	UserID        string
	Title         string
	Content       string
	ScheduledDate string
	StartTime     string
	EndTime       string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	UserID:        "user_id",
	Title:         "title",
	Content:       "content",
	ScheduledDate: "scheduled_date",
	StartTime:     "start_time",
	EndTime:       "end_time",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var ScheduledTaskTableColumns = struct {
	ID            string
	UserID        string
	Title         string
	Content       string
	ScheduledDate string
	StartTime     string
	EndTime       string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "scheduled_task.id",
	UserID:        "scheduled_task.user_id",
	Title:         "scheduled_task.title",
	Content:       "scheduled_task.content",
	ScheduledDate: "scheduled_task.scheduled_date",
	StartTime:     "scheduled_task.start_time",
	EndTime:       "scheduled_task.end_time",
	CreatedAt:     "scheduled_task.created_at",
	UpdatedAt:     "scheduled_task.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ScheduledTaskWhere = struct {
	ID            whereHelperint64
	UserID        whereHelperint
	Title         whereHelpernull_String
	Content       whereHelpernull_String
	ScheduledDate whereHelpertime_Time
	StartTime     whereHelperstring
	EndTime       whereHelperstring
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint64{field: "`scheduled_task`.`id`"},
	UserID:        whereHelperint{field: "`scheduled_task`.`user_id`"},
	Title:         whereHelpernull_String{field: "`scheduled_task`.`title`"},
	Content:       whereHelpernull_String{field: "`scheduled_task`.`content`"},
	ScheduledDate: whereHelpertime_Time{field: "`scheduled_task`.`scheduled_date`"},
	StartTime:     whereHelperstring{field: "`scheduled_task`.`start_time`"},
	EndTime:       whereHelperstring{field: "`scheduled_task`.`end_time`"},
	CreatedAt:     whereHelpertime_Time{field: "`scheduled_task`.`created_at`"},
	UpdatedAt:     whereHelpertime_Time{field: "`scheduled_task`.`updated_at`"},
}

// ScheduledTaskRels is where relationship names are stored.
var ScheduledTaskRels = struct {
	User string
}{
	User: "User",
}

// scheduledTaskR is where relationships are stored.
type scheduledTaskR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*scheduledTaskR) NewStruct() *scheduledTaskR {
	return &scheduledTaskR{}
}

func (r *scheduledTaskR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// scheduledTaskL is where Load methods for each relationship are stored.
type scheduledTaskL struct{}

var (
	scheduledTaskAllColumns            = []string{"id", "user_id", "title", "content", "scheduled_date", "start_time", "end_time", "created_at", "updated_at"}
	scheduledTaskColumnsWithoutDefault = []string{"user_id", "title", "content", "scheduled_date", "start_time", "end_time", "created_at", "updated_at"}
	scheduledTaskColumnsWithDefault    = []string{"id"}
	scheduledTaskPrimaryKeyColumns     = []string{"id"}
	scheduledTaskGeneratedColumns      = []string{}
)

type (
	// ScheduledTaskSlice is an alias for a slice of pointers to ScheduledTask.
	// This should almost always be used instead of []ScheduledTask.
	ScheduledTaskSlice []*ScheduledTask
	// ScheduledTaskHook is the signature for custom ScheduledTask hook methods
	ScheduledTaskHook func(context.Context, boil.ContextExecutor, *ScheduledTask) error

	scheduledTaskQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	scheduledTaskType                 = reflect.TypeOf(&ScheduledTask{})
	scheduledTaskMapping              = queries.MakeStructMapping(scheduledTaskType)
	scheduledTaskPrimaryKeyMapping, _ = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, scheduledTaskPrimaryKeyColumns)
	scheduledTaskInsertCacheMut       sync.RWMutex
	scheduledTaskInsertCache          = make(map[string]insertCache)
	scheduledTaskUpdateCacheMut       sync.RWMutex
	scheduledTaskUpdateCache          = make(map[string]updateCache)
	scheduledTaskUpsertCacheMut       sync.RWMutex
	scheduledTaskUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var scheduledTaskAfterSelectHooks []ScheduledTaskHook

var scheduledTaskBeforeInsertHooks []ScheduledTaskHook
var scheduledTaskAfterInsertHooks []ScheduledTaskHook

var scheduledTaskBeforeUpdateHooks []ScheduledTaskHook
var scheduledTaskAfterUpdateHooks []ScheduledTaskHook

var scheduledTaskBeforeDeleteHooks []ScheduledTaskHook
var scheduledTaskAfterDeleteHooks []ScheduledTaskHook

var scheduledTaskBeforeUpsertHooks []ScheduledTaskHook
var scheduledTaskAfterUpsertHooks []ScheduledTaskHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ScheduledTask) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ScheduledTask) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ScheduledTask) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ScheduledTask) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ScheduledTask) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ScheduledTask) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ScheduledTask) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ScheduledTask) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ScheduledTask) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range scheduledTaskAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddScheduledTaskHook registers your hook function for all future operations.
func AddScheduledTaskHook(hookPoint boil.HookPoint, scheduledTaskHook ScheduledTaskHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		scheduledTaskAfterSelectHooks = append(scheduledTaskAfterSelectHooks, scheduledTaskHook)
	case boil.BeforeInsertHook:
		scheduledTaskBeforeInsertHooks = append(scheduledTaskBeforeInsertHooks, scheduledTaskHook)
	case boil.AfterInsertHook:
		scheduledTaskAfterInsertHooks = append(scheduledTaskAfterInsertHooks, scheduledTaskHook)
	case boil.BeforeUpdateHook:
		scheduledTaskBeforeUpdateHooks = append(scheduledTaskBeforeUpdateHooks, scheduledTaskHook)
	case boil.AfterUpdateHook:
		scheduledTaskAfterUpdateHooks = append(scheduledTaskAfterUpdateHooks, scheduledTaskHook)
	case boil.BeforeDeleteHook:
		scheduledTaskBeforeDeleteHooks = append(scheduledTaskBeforeDeleteHooks, scheduledTaskHook)
	case boil.AfterDeleteHook:
		scheduledTaskAfterDeleteHooks = append(scheduledTaskAfterDeleteHooks, scheduledTaskHook)
	case boil.BeforeUpsertHook:
		scheduledTaskBeforeUpsertHooks = append(scheduledTaskBeforeUpsertHooks, scheduledTaskHook)
	case boil.AfterUpsertHook:
		scheduledTaskAfterUpsertHooks = append(scheduledTaskAfterUpsertHooks, scheduledTaskHook)
	}
}

// One returns a single scheduledTask record from the query.
func (q scheduledTaskQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ScheduledTask, error) {
	o := &ScheduledTask{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for scheduled_task")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ScheduledTask records from the query.
func (q scheduledTaskQuery) All(ctx context.Context, exec boil.ContextExecutor) (ScheduledTaskSlice, error) {
	var o []*ScheduledTask

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ScheduledTask slice")
	}

	if len(scheduledTaskAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ScheduledTask records in the query.
func (q scheduledTaskQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count scheduled_task rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q scheduledTaskQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if scheduled_task exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *ScheduledTask) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (scheduledTaskL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeScheduledTask interface{}, mods queries.Applicator) error {
	var slice []*ScheduledTask
	var object *ScheduledTask

	if singular {
		var ok bool
		object, ok = maybeScheduledTask.(*ScheduledTask)
		if !ok {
			object = new(ScheduledTask)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeScheduledTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeScheduledTask))
			}
		}
	} else {
		s, ok := maybeScheduledTask.(*[]*ScheduledTask)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeScheduledTask)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeScheduledTask))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &scheduledTaskR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &scheduledTaskR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`user`),
		qm.WhereIn(`user.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for user")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.ScheduledTasks = append(foreign.R.ScheduledTasks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.ScheduledTasks = append(foreign.R.ScheduledTasks, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the scheduledTask to the related item.
// Sets o.R.User to related.
// Adds o to related.R.ScheduledTasks.
func (o *ScheduledTask) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `scheduled_task` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"user_id"}),
		strmangle.WhereClause("`", "`", 0, scheduledTaskPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &scheduledTaskR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			ScheduledTasks: ScheduledTaskSlice{o},
		}
	} else {
		related.R.ScheduledTasks = append(related.R.ScheduledTasks, o)
	}

	return nil
}

// ScheduledTasks retrieves all the records using an executor.
func ScheduledTasks(mods ...qm.QueryMod) scheduledTaskQuery {
	mods = append(mods, qm.From("`scheduled_task`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`scheduled_task`.*"})
	}

	return scheduledTaskQuery{q}
}

// FindScheduledTask retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindScheduledTask(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ScheduledTask, error) {
	scheduledTaskObj := &ScheduledTask{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `scheduled_task` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, scheduledTaskObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from scheduled_task")
	}

	if err = scheduledTaskObj.doAfterSelectHooks(ctx, exec); err != nil {
		return scheduledTaskObj, err
	}

	return scheduledTaskObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ScheduledTask) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no scheduled_task provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduledTaskColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	scheduledTaskInsertCacheMut.RLock()
	cache, cached := scheduledTaskInsertCache[key]
	scheduledTaskInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			scheduledTaskAllColumns,
			scheduledTaskColumnsWithDefault,
			scheduledTaskColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `scheduled_task` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `scheduled_task` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `scheduled_task` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, scheduledTaskPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into scheduled_task")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == scheduledTaskMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for scheduled_task")
	}

CacheNoHooks:
	if !cached {
		scheduledTaskInsertCacheMut.Lock()
		scheduledTaskInsertCache[key] = cache
		scheduledTaskInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ScheduledTask.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ScheduledTask) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	scheduledTaskUpdateCacheMut.RLock()
	cache, cached := scheduledTaskUpdateCache[key]
	scheduledTaskUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			scheduledTaskAllColumns,
			scheduledTaskPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update scheduled_task, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `scheduled_task` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, scheduledTaskPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, append(wl, scheduledTaskPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update scheduled_task row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for scheduled_task")
	}

	if !cached {
		scheduledTaskUpdateCacheMut.Lock()
		scheduledTaskUpdateCache[key] = cache
		scheduledTaskUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q scheduledTaskQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for scheduled_task")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for scheduled_task")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ScheduledTaskSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduledTaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `scheduled_task` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, scheduledTaskPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in scheduledTask slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all scheduledTask")
	}
	return rowsAff, nil
}

var mySQLScheduledTaskUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ScheduledTask) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no scheduled_task provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(scheduledTaskColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLScheduledTaskUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	scheduledTaskUpsertCacheMut.RLock()
	cache, cached := scheduledTaskUpsertCache[key]
	scheduledTaskUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			scheduledTaskAllColumns,
			scheduledTaskColumnsWithDefault,
			scheduledTaskColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			scheduledTaskAllColumns,
			scheduledTaskPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert scheduled_task, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`scheduled_task`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `scheduled_task` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for scheduled_task")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == scheduledTaskMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(scheduledTaskType, scheduledTaskMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for scheduled_task")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for scheduled_task")
	}

CacheNoHooks:
	if !cached {
		scheduledTaskUpsertCacheMut.Lock()
		scheduledTaskUpsertCache[key] = cache
		scheduledTaskUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ScheduledTask record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ScheduledTask) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ScheduledTask provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), scheduledTaskPrimaryKeyMapping)
	sql := "DELETE FROM `scheduled_task` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from scheduled_task")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for scheduled_task")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q scheduledTaskQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no scheduledTaskQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from scheduled_task")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for scheduled_task")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ScheduledTaskSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(scheduledTaskBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduledTaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `scheduled_task` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, scheduledTaskPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from scheduledTask slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for scheduled_task")
	}

	if len(scheduledTaskAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ScheduledTask) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindScheduledTask(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ScheduledTaskSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ScheduledTaskSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), scheduledTaskPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `scheduled_task`.* FROM `scheduled_task` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, scheduledTaskPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ScheduledTaskSlice")
	}

	*o = slice

	return nil
}

// ScheduledTaskExists checks if the ScheduledTask row exists.
func ScheduledTaskExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `scheduled_task` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if scheduled_task exists")
	}

	return exists, nil
}

// Exists checks if the ScheduledTask row exists.
func (o *ScheduledTask) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ScheduledTaskExists(ctx, exec, o.ID)
}
