// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testShareTasks(t *testing.T) {
	t.Parallel()

	query := ShareTasks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testShareTasksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testShareTasksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ShareTasks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testShareTasksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ShareTaskSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testShareTasksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ShareTaskExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ShareTask exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ShareTaskExists to return true, but got false.")
	}
}

func testShareTasksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	shareTaskFound, err := FindShareTask(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if shareTaskFound == nil {
		t.Error("want a record, got nil")
	}
}

func testShareTasksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ShareTasks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testShareTasksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ShareTasks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testShareTasksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	shareTaskOne := &ShareTask{}
	shareTaskTwo := &ShareTask{}
	if err = randomize.Struct(seed, shareTaskOne, shareTaskDBTypes, false, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}
	if err = randomize.Struct(seed, shareTaskTwo, shareTaskDBTypes, false, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = shareTaskOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = shareTaskTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ShareTasks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testShareTasksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	shareTaskOne := &ShareTask{}
	shareTaskTwo := &ShareTask{}
	if err = randomize.Struct(seed, shareTaskOne, shareTaskDBTypes, false, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}
	if err = randomize.Struct(seed, shareTaskTwo, shareTaskDBTypes, false, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = shareTaskOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = shareTaskTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func shareTaskBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func shareTaskAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ShareTask) error {
	*o = ShareTask{}
	return nil
}

func testShareTasksHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ShareTask{}
	o := &ShareTask{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, shareTaskDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ShareTask object: %s", err)
	}

	AddShareTaskHook(boil.BeforeInsertHook, shareTaskBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	shareTaskBeforeInsertHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.AfterInsertHook, shareTaskAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	shareTaskAfterInsertHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.AfterSelectHook, shareTaskAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	shareTaskAfterSelectHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.BeforeUpdateHook, shareTaskBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	shareTaskBeforeUpdateHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.AfterUpdateHook, shareTaskAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	shareTaskAfterUpdateHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.BeforeDeleteHook, shareTaskBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	shareTaskBeforeDeleteHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.AfterDeleteHook, shareTaskAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	shareTaskAfterDeleteHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.BeforeUpsertHook, shareTaskBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	shareTaskBeforeUpsertHooks = []ShareTaskHook{}

	AddShareTaskHook(boil.AfterUpsertHook, shareTaskAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	shareTaskAfterUpsertHooks = []ShareTaskHook{}
}

func testShareTasksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testShareTasksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(shareTaskColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testShareTaskToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ShareTask
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, shareTaskDBTypes, false, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := ShareTaskSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*ShareTask)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testShareTaskToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ShareTask
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, shareTaskDBTypes, false, strmangle.SetComplement(shareTaskPrimaryKeyColumns, shareTaskColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ShareTasks[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testShareTasksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testShareTasksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ShareTaskSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testShareTasksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ShareTasks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	shareTaskDBTypes = map[string]string{`ID`: `bigint`, `UserID`: `int`, `SharedUserID`: `int`, `SharedStatus`: `int`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_                = bytes.MinRead
)

func testShareTasksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(shareTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(shareTaskAllColumns) == len(shareTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testShareTasksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(shareTaskAllColumns) == len(shareTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ShareTask{}
	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, shareTaskDBTypes, true, shareTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(shareTaskAllColumns, shareTaskPrimaryKeyColumns) {
		fields = shareTaskAllColumns
	} else {
		fields = strmangle.SetComplement(
			shareTaskAllColumns,
			shareTaskPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ShareTaskSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testShareTasksUpsert(t *testing.T) {
	t.Parallel()

	if len(shareTaskAllColumns) == len(shareTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLShareTaskUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ShareTask{}
	if err = randomize.Struct(seed, &o, shareTaskDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ShareTask: %s", err)
	}

	count, err := ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, shareTaskDBTypes, false, shareTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ShareTask struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ShareTask: %s", err)
	}

	count, err = ShareTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
