default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: host.docker.internal
  username: root
  password: root

development:
  <<: *default
  database: tasktree

test:
  <<: *default
  host: localhost:3306
  database: tasktree_test

github:
  <<: *default
  host: 127.0.0.1:3306
  database: tasktree_ci
