// Code generated by MockGen. DO NOT EDIT.
// Source: base_tasks.go

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/watariRyo/tasktree/server/domain/model"
	repository "github.com/watariRyo/tasktree/server/domain/repository"
)

// MockBaseTasksRepository is a mock of BaseTasksRepository interface.
type MockBaseTasksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBaseTasksRepositoryMockRecorder
}

// MockBaseTasksRepositoryMockRecorder is the mock recorder for MockBaseTasksRepository.
type MockBaseTasksRepositoryMockRecorder struct {
	mock *MockBaseTasksRepository
}

// NewMockBaseTasksRepository creates a new mock instance.
func NewMockBaseTasksRepository(ctrl *gomock.Controller) *MockBaseTasksRepository {
	mock := &MockBaseTasksRepository{ctrl: ctrl}
	mock.recorder = &MockBaseTasksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseTasksRepository) EXPECT() *MockBaseTasksRepositoryMockRecorder {
	return m.recorder
}

// GetBaseTaskByUserID mocks base method.
func (m *MockBaseTasksRepository) GetBaseTaskByUserID(ctx context.Context, conn repository.DBConnection, userID int) (*model.BaseTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseTaskByUserID", ctx, conn, userID)
	ret0, _ := ret[0].(*model.BaseTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseTaskByUserID indicates an expected call of GetBaseTaskByUserID.
func (mr *MockBaseTasksRepositoryMockRecorder) GetBaseTaskByUserID(ctx, conn, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseTaskByUserID", reflect.TypeOf((*MockBaseTasksRepository)(nil).GetBaseTaskByUserID), ctx, conn, userID)
}

// Insert mocks base method.
func (m *MockBaseTasksRepository) Insert(ctx context.Context, conn repository.DBConnection, input *model.BaseTask) (*model.BaseTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, conn, input)
	ret0, _ := ret[0].(*model.BaseTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockBaseTasksRepositoryMockRecorder) Insert(ctx, conn, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockBaseTasksRepository)(nil).Insert), ctx, conn, input)
}
